### ISSUE TITLE
Otio reader app: Some flavours of video codec don't appear to work

### ISSUE THREAD

**Issue by TrevorAyl** [Synopsis/OpenTimelineIO-AVFoundation#26]
Only the ProRes bars make it from a Resolve OTIO export to being viewed in the Otio reader app. ('Media not supported')

Zipped file has the bars and an Otio. 

[Bars of various flavours.zip](https://github.com/user-attachments/files/17619532/Bars.of.various.flavours.zip)

I installed the [Pro Video Formats](https://support.apple.com/en-us/106396) but no change.

**Comment by vade** [comment]
Thanks! ill look into this!

**Comment by vade** [comment]
Fixed in the dev branch. Found some silly and some subtle bugs. All your media loads and plays for me now:

![image](https://github.com/user-attachments/assets/48e93ecc-5ad1-42a9-87f1-54c7f1ba01ab)

**Comment by vade** [comment]
Ill put out a new release shortly.

**Comment by vade** [comment]
https://github.com/Synopsis/OpenTimelineIO-AVFoundation/releases/tag/releases%2F1.0-Beta-4 :) 

Thanks for reporting the issue @TrevorAyl
